version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: docker build
          command: ./scripts/build_xmr-stak_docker/circle_xmr-stak_docker.sh
      - run:
          name: run the benchmarks
          command: ./bin/xmr-stak --benchmark
      - run:
          name: Print the Current Time
          command: date
